### ISSUE TITLE
PostgreSQL para sustituir a MongoDB y MySQL

### ISSUE THREAD

**Issue by danirod** [rubendelblanco/openrpg#12]
PostgreSQL, además de ser una base de datos relacional como MySQL, tiene soporte nativo para documentos JSONB y pueden hacerse queries a partir de keys de un documento JSON, como hace MongoDB.

**Comment by sonirico** [comment]
Por no decir que tiene de base key-value store y otras features que tornan esta herramienta como buena navaja suiza en esta fase de prototipacion.

**Comment by danirod** [comment]
[p u b s u b](https://www.postgresql.org/docs/9.1/sql-notify.html)

**Comment by rubendelblanco** [comment]
He leído por encima algunas cosas y parece que Eloquent también vale para postgreSQL con lo que *PARECE* que solo hay que cambiar la configuración en database.php.
Os dejo esta tarea a vosotros que controláis más.

**Comment by rubendelblanco** [comment]
Cierro el issue #2
