### ISSUE TITLE
Crear Campañas y Aventuras

### ISSUE THREAD

**Issue by rubendelblanco** [rubendelblanco/openrpg#4]
Campaign:
- Id
- UserId (relación a user que dirige la campaña)
- Title
- Description

Character:
- Id
- UserId
- CharacterSheet (un link a la hoja de personaje que irá en Mongo)
- Avatar (URL a imagen)

Un personaje (character) puede estar en más de una campaña. Hay que hacer una tabla pivote ahí.

**Comment by rubendelblanco** [comment]
Olvida el modelo Character porque ya no vamos a usar Mongo. Ese problema irá ahora ligado al milestone https://github.com/rubendelblanco/openrpg/milestones

En vez de eso, hagamos lo siguiente

Campaign (eso no cambia):
- Id
- UserId (relación con usuario que dirige la campaña)
- Title
- Description

Adventure, esto irá relacionado con una campaña. En una campaña habrá varias aventuras. Así que la tabla sería:
- Id
- CampaignId
- Title
- Description

En futuras tablas que iremos incorporando puede que relacionemos recursos con una aventura en concreto. Por ejemplo: combates, mapas y objetos. Ayudaría mucho a localizar las cosas pasado un tiempo. Por ejemplo, ocurre mucho que alguien encuentra un objeto especial y luego, por motivo X, tenemos que hacer memoria para saber dónde se encontró. Si podemos relacionar ese objeto con la aventura el máster puede localizarlo rápido y así perder menos tiempo. Esto es especulación aun pero puede tener su utilidad.

**Comment by danirod** [comment]
Updating issue title to reflect the current state of the task. I drew this after reading both comments, it seems that the goal of the task is to have both models on the right side.

![998EEA26-2B95-4E4D-80C3-B419BFF39345_1_101_o](https://user-images.githubusercontent.com/1568690/68548557-68964600-03ee-11ea-98d6-04a0adef345c.jpeg)
