### ISSUE TITLE
Deprecar el Django

### ISSUE THREAD

**Issue by danirod** [rubendelblanco/openrpg#54]
Bloqueada por danirod/openrpg-ui#3.

Una vez haya un CRUD frontal para manipular los spells, se puede deprecar el Django que se montó para poder tener un panel de edición. Igual hay que meter antes el backend que permita crear y eliminar estos spells, pero posible lo veo y puede que con la form-generator se pueda hacer rápido con un esquema.

Que sí, que ya sé que cepillarse el Django es un objetivo de todos modos, pero lo plasmo en un ticket para que no se olvide.

**Comment by sonirico** [comment]
pero esta mezclado si quiera? pensaba que se habia quedado en la rama feature xD

**Comment by danirod** [comment]
Arreglado en #69.
