### ISSUE TITLE
Modelo de hechizos

### ISSUE THREAD

**Issue by rubendelblanco** [rubendelblanco/openrpg#7]
Los hechizos constan de varias características. Además están en listas (pueden ser abiertas, cerradas o básicas) y estas listas a su vez pertenecen a un reino (Mentalismo, Canalización, Esencia o Arcana). Los hechizos poseen estos campos:
- Nombre
- Nivel
- Area de efecto
- Duración
- Rango
- Tipo
- Descripción
- Notas

**Comment by danirod** [comment]
¿Esto no está implementado ya en https://github.com/rubendelblanco/openrpg/blob/de299c3958431b46260599542eb66797e9b576e9/database/migrations/2020_01_05_124105_create_spells_table.php? /cc @sonirico

**Comment by sonirico** [comment]
back si, front no (https://github.com/rubendelblanco/openrpg/issues/54)
